### ISSUE TITLE
Build compatible with client-lib 1.7.3?

### ISSUE THREAD

**Issue by tnixon** [awslabs/dynamodb-streams-kinesis-adapter#12]
Would it be possible to get a build of this project that is compatible with kinesis-client 1.73 (AWS SDK 1.11.76)?

I am working on integrating the DDB stream adapter into Spark so that spark streaming apps can read from a DDB stream. They are currently using SDK version 1.11.76 and kinesis-client 1.7.3 (I think mostly due to constraints of being compatible with Hadoop). The ddb-streams 1.1.1 build is compatible from 1.6.4 to 1.7.0 and the 1.2.0 build from 1.7.5 to 1.8.0, but no builds are compatible with 1.7.3. It would really help me out if there was a build available that was compatible in the 1.70-1.7.5 range.

Thanks!

**Comment by tnixon** [comment]
I'd be happy to get a compatible version in my fork and perhaps you could pull it in as a separate branch.

**Comment by amcp** [comment]
Please submit a pull request. 
FWIW, what is stopping you from dropping your own custom jars that support 1.7.3 in your fork?
Is it as easy as just dropping the version range in pom.xml? Or is this change more complicated?

**Comment by tnixon** [comment]
I really hope it's not more complicated - it would be very nice if that's all I need to do :)

**Comment by amcp** [comment]
I coded [support for 1.7.3](https://github.com/awslabs/dynamodb-streams-kinesis-adapter/tree/kcl1.7.3) but you will have to build and consume it on your side.
