### ISSUE TITLE
Question: Is the AmazonDynamoDBStreamsAdapterClient threadsafe?

### ISSUE THREAD

**Issue by joelittlejohn** [awslabs/dynamodb-streams-kinesis-adapter#14]
I have an application that consumes multiple DynamoDB streams from different tables. I'd like to reuse stateless clients where I can.

Is it acceptable to create different KCL workers that use the same AmazonDynamoDBStreamsAdapterClient instance, where each worker is consuming a different table stream?

**Comment by joelittlejohn** [comment]
Anyone have any comment on this?

**Comment by agarbutt** [comment]
any update on this question?

**Comment by aggarwal** [comment]
Yes, `AmazonDynamoDBStreamsAdapterClient` is thread safe. It is accessed concurrently by `ProcessTask` instances inside the KCL worker. There are only two instance variables in the class: `internalClient` and `requestCache`. The variable `internalClient` is an AWS SDK client, which is thread safe. The second variable `requestCache` holds a reference to a HashMap, but mutating methods use the `synchronized` keyword.
