### ISSUE TITLE
Overwrites Endpoint Set

### ISSUE THREAD

**Issue by dayyan** [awslabs/dynamodb-streams-kinesis-adapter#18]
I've been trying to use this with DynamoDB Local. I set the endpoint to my localhost and the correct port but the KCL keeps hitting us-west-2.

I tried throwing an immutable DynamoDB Stream client into `AmazonDynamoDBStreamsAdapterClient`. This causes the immutable client error (can't set).

**Comment by aggarwal** [comment]
I tested using KCL 1.13.3 and Adapter 1.5.2 with DynamoDB Local today, and it worked as expected.
Please try with these version. If you're still experiencing the issue, please submit the code here to reproduce the issue.
