### ISSUE TITLE
Will not build with AmazonDynamoDBStreamsAdapterClient is not abstract

### ISSUE THREAD

**Issue by jasonrichardsmith** [awslabs/dynamodb-streams-kinesis-adapter#3]
AmazonDynamoDBStreamsAdapterClient.java:[75,7] error: AmazonDynamoDBStreamsAdapterClient is not abstract and does not override abstract method enableEnhancedMonitoring(EnableEnhancedMonitoringRequest) in AmazonKinesis

**Comment by avinash8526** [comment]
+1 it doesn't build throws error on mvn clean install

**Comment by chappidmAWS** [comment]
+1 for mvn clean install

**Comment by amcp** [comment]
I just checked out the repository in /tmp and issued `mvn clean install`. The package built. I used JDK 8. Closing.

**Comment by amcp** [comment]
Fixed in #11
