### ISSUE TITLE
amazon-kinesis-client 1.13.3 breaks dynamodb-streams-kinesis-adapter

### ISSUE THREAD

**Issue by solo-yolo** [awslabs/dynamodb-streams-kinesis-adapter#31]
Hi, this issue pretty similar to #27, newly released version of amazon-kinesis-client, namely [1.13.3](https://github.com/awslabs/amazon-kinesis-client/releases/tag/v1.13.3) introduced compatibility issue with dynamodb-streams-kinesis-adapter.

Incompatibility caused by adding a new method to the `IKinesisProxy` interface [(link)](https://github.com/awslabs/amazon-kinesis-client/pull/684/files#diff-833df03b324a9cfac74b25ded152b023)

It leads to the following error:
```
com.amazonaws.services.dynamodbv2.streamsadapter.DynamoDBStreamsProxy does not define or inherit an implementation of the resolved method 'abstract com.amazonaws.services.kinesis.clientlibrary.proxies.ShardClosureVerificationResponse verifyShardClosure(java.lang.String)' of interface com.amazonaws.services.kinesis.clientlibrary.proxies.IKinesisProxy.
\tat com.amazonaws.services.kinesis.clientlibrary.lib.worker.ShutdownTask.call(ShutdownTask.java:108)
...
```

As @tmszdmsk already mentioned, as a temporary solution it can be fixed by changing version range to the `1.13.2`

**Comment by aggarwal** [comment]
This issue has been resolved now in the 1.5.1 release. We've also fixed the KCL dependency at 1.13.1 to avoid this in the future.
