### ISSUE TITLE
[General Question]: Can i use this in AWS Lambda? 

### ISSUE THREAD

**Issue by santhosh34** [awslabs/dynamodb-streams-kinesis-adapter#34]
Can we use this logic to process the stream of records in AWS Lambda? How can we manage the time limit if huge stream data?

**Comment by aggarwal** [comment]
AWS Lambda natively supports reading data from DynamoDB Streams, and you should be using that support directly. 

See: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Streams.Lambda.html

We advise against using the DynamoDB Streams Kinesis Adapter and Kinesis Client Library (KCL) in a Lambda function as KCL is a long running process, and Lambda functions should generally be short lived.
