### ISSUE TITLE
KCL is unable to renew the lease due to an issue calling renewLeases

### ISSUE THREAD

**Issue by rl1m4** [awslabs/dynamodb-streams-kinesis-adapter#36]
There is an internal server error during the lifetime of a table - an exception indicating that the KCL is unable to renew the lease due to an issue calling renewLeases on the application's lease table (kinesis library having issue talking to DynamoDB).

The worker tries to renewLeases and throws a log error: Encountered and exception while renewing a lease (it increases a lease to 1).

```"message":"LeasingException encountered in lease renewing thread”```
```"stack_trace":"com.amazonaws.services.kinesis.leases.exceptions.DependencyException: Encountered an exception while renewing leases.."```

amazon-kinesis-client:1.9.1
aws-java-sdk-dynamodb:1.11.382
dynamodb-streams-kinesis-adapter:1.4.0

Any idea how to fix it?
Thanks

**Comment by aggarwal** [comment]
Please upgrade to version 1.5.1 of dynamodb-streams-kinesis-adapter, and let us know if you see the same issue.

**Comment by rl1m4** [comment]
> Please upgrade to version 1.5.1 of dynamodb-streams-kinesis-adapter, and let us know if you see the same issue.

Could you give me more details about the changes on 1.5.1 version that can fix this issue?
