### ISSUE TITLE
UnsupportedClassVersionError for Java 7 runtime

### ISSUE THREAD

**Issue by snallami** [awslabs/dynamodb-streams-kinesis-adapter#4]
Getting below error

[2016-07-08 00:38:25.352 EDT] <localhost-startStop-1> o.s.b.SpringApplication - ERROR: Application startup failed
java.lang.UnsupportedClassVersionError: com/amazonaws/services/kinesis/clientlibrary/interfaces/IRecordProcessorFactory : Unsupported major.minor version 52.0 (unable to load class com.amazonaws.services.kinesis.clientlibrary.interfaces.IRecordProcessorFactory)
        at org.apache.catalina.loader.WebappClassLoader.findClassInternal(WebappClassLoader.java:3111) ~[catalina.jar:7.0.64]
        at org.apache.catalina.loader.WebappClassLoader.findClass(WebappClassLoader.java:1348) ~[catalina.jar:7.0.64]
        at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1828) ~[catalina.jar:7.0.64]
        at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1709) ~[catalina.jar:7.0.64]

Root Cause: amazon-kinesis-client 1.6.4 version is released on July 6th, 2016 and looks like it is compiled with JDK 1.8

 In pom.xml , am not sure why you are defining version range for amazon-kinesis-client instead of depending on a fixed version. This is causing unexpected errors like this all of a sudden
<amazon-kinesis-client.version>[1.6.0, 1.7.0)</amazon-kinesis-client.version>

**Comment by amcp** [comment]
looking at the [1.6.4 tag of KCL pom.xml](https://github.com/awslabs/amazon-kinesis-client/blob/v1.6.4/pom.xml#L86) shows that source needs to be compatible with 1.7 and the compilation target is also 1.7. I will check the JAR binary next.

**Comment by amcp** [comment]
$ mkdir temp && cd temp && wget http://central.maven.org/maven2/com/amazonaws/amazon-kinesis-client/1.6.4/amazon-kinesis-client-1.6.4.jar
$ jar xf amazon-kinesis-client-1.6.4.jar
$ file com/amazonaws/services/kinesis/clientlibrary/lib/worker/KinesisClientLibLeaseCoordinator.class 
com/amazonaws/services/kinesis/clientlibrary/lib/worker/KinesisClientLibLeaseCoordinator.class: compiled Java class data, version 52.0 (Java 1.8)

**Comment by amcp** [comment]
Congratulations on finding this issue. However, this is an issue with KCL and not the dynamodb-streams-kinesis-adapter. JDK7 is deprecated and it is recommended to use JDK8. I will file this issue with the KCL project.

**Comment by amcp** [comment]
https://github.com/awslabs/amazon-kinesis-client/issues/162
