### ISSUE TITLE
Issues copying the project dependencies through maven due to DynamoDBLocal's last release being published in a repository other than the specified in the POM

### ISSUE THREAD

**Issue by pablocostass** [awslabs/dynamodb-streams-kinesis-adapter#56]
`dynamodb-streams-kinesis-adapter` has included as a test-only dependency in its POM [`DynamoDBLocal`](https://mvnrepository.com/artifact/com.amazonaws/DynamoDBLocal). I have noticed at work, as we use this project, that a system of ours could not be built any longer because the version constraint the kinesis adapter has for the test dependency is that of `[1.12,2.0)`, and the latest valid 1.XX.X release (`1.24.0`, as per the [Release history for DynamoDB local](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocalHistory.html) site says) has not been uploaded to the repository specified in the POM for the dependency:

https://github.com/awslabs/dynamodb-streams-kinesis-adapter/blob/4fc3d79a0a0ea51b05175510b4cbd7daaa286587/pom.xml#L227-L236

This can be replicated running the following snippet:
```bash
$ mkdir /tmp/jars
$ curl -L -o /tmp/jars/dynamodb-streams-kinesis-adapter-1.5.3.pom http://search.maven.org/remotecontent?filepath=com/amazonaws/dynamodb-streams-kinesis-adapter/1.5.3/dynamodb-streams-kinesis-adapter-1.5.3.pom
$ mvn -B -f /tmp/jars/dynamodb-streams-kinesis-adapter-1.5.3.pom dependency:copy-dependencies -DoutputDirectory=/tmp/jars -DincludeScope=runtime
```

The issue is still present with the latest release of the kinesis adapter.

**Comment by shetsa-amzn** [comment]
This should fix it: https://github.com/awslabs/dynamodb-streams-kinesis-adapter/pull/58

**Comment by pablocostass** [comment]
Thanks!

**Comment by gguptp** [comment]
The latest release of the adpater (1.6.1) fixes this issue
