### ISSUE TITLE
Add support for the latest KCL versions (>1.7.1)

### ISSUE THREAD

**Issue by jdoc** [awslabs/dynamodb-streams-kinesis-adapter#6]
Using this library in conjunction with KCL 1.7.3 is not possible currently. Since the signature and package of several classes
e.g.
`com.amazonaws.services.kinesis.clientlibrary.types.ShutdownReason`
moved to 
`com.amazonaws.services.kinesis.clientlibrary.lib.worker.ShutdownReason`
In my project, I use the latest KCL and have to exclude the KCL included in dynamodb-streams-kinesis-adapter, this causes compilation errors to happen.

**Comment by amcp** [comment]
We [updated to KCL 1.7.5](https://github.com/awslabs/dynamodb-streams-kinesis-adapter/tree/1.2.0) today.
