### ISSUE TITLE
Should have a builder

### ISSUE THREAD

**Issue by tnixon** [awslabs/dynamodb-streams-kinesis-adapter#8]
There should be a builder for AmazonDynamoDBStreamsAdapterClients that returns an instance as a generic AmazonKinesis object.

**Comment by tnixon** [comment]
I've created a pull request (#9) for this:
https://github.com/awslabs/dynamodb-streams-kinesis-adapter/pull/9

**Comment by amcp** [comment]
Why should there be a builder?

**Comment by tnixon** [comment]
It seems like it's the dominant pattern across AWS libs, so why not have one?

**Comment by aggarwal** [comment]
Closing as the PR has been inactive for 3+ years.
